# see https://github.com/sigoden/aichat/blob/main/config.example.yaml

model: github:gpt-4o
clients:
- type: openai-compatible
  name: github
  api_base: https://models.inference.ai.azure.com
  api_key: ""
