
[font]
size = 12.0

[font.bold]
family = "Hack Nerd Font"

[font.bold_italic]
family = "Hack Nerd Font"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Hack Nerd Font"

[font.normal]
family = "Hack Nerd Font"

[font.offset]
x = 0
y = 0

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[terminal.shell]
program = "fish"

[window]
decorations = "none"
dynamic_padding = true

[window.padding]
x = 8
y = 8

[general]
import = ["/home/shidil/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[terminal]
